version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - aws s3 rm s3://ganglin.net --recursive
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: "dist"
